---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration
  namespace: 3edges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
        prom: prom-3edges
    spec:
      containers:
        - name: configuration
          imagePullPolicy: Always
          image: us-docker.pkg.dev/edges-305901/gcr.io/prim-configuration:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: SERVER_PORT
              value: "4005"
            - name: ENABLE_INTROSPECTION
              value: "true"
            - name: ENABLE_PLAYGROUND
              value: "true"
            - name: REACT_APP_OTP_VALIDITY
              value: "2880"
            - name: SEND_EMAIL_FROM
              value: "noreply@3edges.io"
            - name: SEND_EMAIL_FROM_NAME
              value: "3Edges"
            - name: SEND_EMAIL_URL
              value: "https://edges-305901.uw.r.appspot.com/api"
            - name: NEO4J_POOL_SIZE
              value: "300"
            - name: NEO4J_CONNECTION_ACQUISITION_TIMEOUT_MS
              value: "60000"
            - name: NEO4J_MAX_CONNECTION_LIFETIME
              value: "3600000"
            - name: NEO4J_CONNECTION_TIMEOUT
              value: "30000"
            - name: RESET_ADMIN_USER
              value: "false"
            - name: PRIM_ADMIN_EMAIL
              value: "3admin@3edges.io"
            - name: NEO4J_URL_TEST
              value: "neo4j+s://9d49f282.databases.neo4j.io"
            - name: NEO4J_PASSWORD_TEST
              valueFrom:
                secretKeyRef:
                  key: NEO4J_PASSWORD_TEST
                  name: prim-configuration-secret
            - name: PRIM_CONFIG_NEO4J_DB_TEST
              value: "neo4j"
            - name: PRIM_SERVER_HTTP_CORS_ORIGIN
              value: "https://3edges.io"
            - name: PRIM_SERVER_HTTP_CORS_DEFAULT_ORIGIN
              value: "https://3edges.io"
            - name: DB_TYPE
              value: "neo4j"
            - name: DB_VERSION
              value: "v4"
            - name: DB_HOST
              value: "neo4j+s://db2.3edges.io:7687"
            - name: DB_NAME
              value: "threeedges"
            - name: DB_USER
              value: "neo4j"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEO4J_PASSWORD
                  name: prim-configuration-secret
            - name: PRIM_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  key: PRIM_ADMIN_PASS
                  name: prim-configuration-secret
            - name: PRIM_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: PRIM_JWT_SECRET
                  name: prim-configuration-secret
            - name: OIDC_URL
              value: "https://idp.3edges.io/oidc"
            - name: OIDC_CLIENT_ID
              value: "3edgesConfigClient"
            - name: OIDC_CLIENT_PWD
              valueFrom:
                secretKeyRef:
                  key: OIDC_CLIENT_PWD
                  name: prim-configuration-secret
            - name: CLUSTER_URL
              value: "https://cluster.3edges.io/api"
            - name: COOKIE_NNCE
              value: "nnce"
            - name: COOKIE_PRIMSCOOKIE
              value: "primscookie"
            - name: COOKIE_PKEY
              value: "pkey"
            - name: REDIS_HOST
              value: "redis-headless"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_TIMEOUT_GET_APISERVER_STATUS
              value: "30"
            - name: LOCALHOST_PROXY_DASHBOARD_URL
              value: null
            - name: LOCALHOST_PROXY_IDP_URL
              value: null
            - name: LOCALHOST_PROXY_AUTHORIZATION_URL
              value: null
            - name: AUTHZ_POD_PORT
              value: "5055"
            - name: DASHBOARD_POD_PORT
              value: "3045"
            - name: IDP_POD_PORT
              value: "3001"
            - name: PROXY_POD_PORT
              value: "4044"
            - name: TOKEN_PIPELINE
              value: "ccea8377-61b4-49aa-91f5-c312de02d5f3"
            - name: DEFAULT_CONTENT_SECURITY_POLICY_API_DASHBOARD
              value: default-src 'self' *.3edges.io *.qa.3edges.io https://auth-qa.credivera.com https://vc-qa.credivera.io https://ipv4.icanhazip.com https://api.ipify.com;
                script-src 'self' http://conoret.com https://www.recaptcha.net https://recaptcha.net https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://www.google.com/recaptcha/ 'unsafe-inline' 'unsafe-eval';
                img-src 'self' www.gstatic.com/recaptcha data:; font-src 'self' https://fonts.gstatic.com;
                frame-src 'self' *.recaptcha.net recaptcha.net https://www.google.com/recaptcha/ https://recaptcha.google.com;
                style-src 'self' https://fonts.googleapis.com 'unsafe-inline';
            - name: SESSION_PIPELINE
              value: "ea95ac2e-ea05-4ddd-8aba-bf41ba2ddd86"
            - name: MAX_SHUTDOWN
              value: "20"
            - name: MAX_REDEPLOY
              value: "5"
            - name: SEND_EMAIL_SERVER
              value: "PROD"
            - name: INTERNAL_SECRET
              value: "x-secret"
            - name: COST_LIMIT_ENABLED
              value: "true"
            - name: COST_LIMIT_MAXCOST
              value: "300000"
            - name: COST_LIMIT_OBJECTCOST
              value: "5"
            - name: COST_LIMIT_SCALARCOST
              value: "5"
            - name: COST_LIMIT_DEPTHCOSTFACTOR
              value: "2"
            - name: COST_LIMIT_IGNOREINTROSPECTION
              value: "true"
            - name: COST_LIMIT_N
              value: "20"
            - name: MAX_ALIASES_ENABLED
              value: "true"
            - name: MAX_ALIASES_N
              value: "20"
            - name: MAX_DIRECTIVES_N
              value: "20"
            - name: MAX_DEPTH_N
              value: "8"
            - name: MAX_TOKENS_N
              value: "250"
            - name: PRIM_SERVER_HTTP_CORS_ORIGIN_IDP
              value: "https://idp.3edges.io"
            - name: MAX_CHARACTERS_N
              value: "15000"
            - name: PROCESS_TIMEOUT_N
              value: "10000"
            - name: UI_PROCESS_TIMEOUT_N
              value: "100000"
            - name: DB_RECORDS_BATCH_SIZE
              value: "10"
            - name: QUERY_COMPLEXITY_LIMIT
              value: "140000"
            - name: DEFAULT_CONTENT_SECURITY_POLICY
              value: default-src 'self' *.3edges.io *.qa.3edges.io https://embeddable-sandbox.cdn.apollographql.com/ https://auth-qa.credivera.com https://vc-qa.credivera.io https://ipv4.icanhazip.com https://api.ipify.com https://apollo-server-landing-page.cdn.apollographql.com;
                script-src 'self' https://embeddable-sandbox.cdn.apollographql.com/ http://conoret.com https://www.recaptcha.net https://recaptcha.net https://www.gstatic.com/recaptcha/ https://www.gstatic.cn/recaptcha/ https://www.google.com/recaptcha/ https://apollo-server-landing-page.cdn.apollographql.com/ 'unsafe-inline' 'unsafe-eval';
                img-src 'self' www.gstatic.com/recaptcha https://apollo-server-landing-page.cdn.apollographql.com data:;
                frame-src 'self' https://sandbox.embed.apollographql.com/ *.recaptcha.net recaptcha.net https://www.google.com/recaptcha/ https://recaptcha.google.com https://apollo-server-landing-page.cdn.apollographql.com;
                style-src 'self' https://fonts.googleapis.com https://apollo-server-landing-page.cdn.apollographql.com 'unsafe-inline';
                font-src 'self' https://fonts.gstatic.com https://apollo-server-landing-page.cdn.apollographql.com;
            - name: UI_URL
              value: "https://3edges.io"
