---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataloader
  namespace: 3edges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataloader
  template:
    metadata:
      labels:
        app: dataloader
        prom: prom-3edges
    spec:
      containers:
      - name: dataloader
        imagePullPolicy: Always
        image: us-docker.pkg.dev/edges-305901/gcr.io/prim-dataloader:latest
        env:
          - name: NODE_ENV
            value: "production"
          - name: CORS_ORIGIN
            value: "*"
          - name: PORT
            value: "3000"
          - name: NEO4J_POOL_SIZE
            value: "300"
          - name: NEO4J_CONNECTION_ACQUISITION_TIMEOUT_MS
            value: "60000"
          - name: NEO4J_MAX_CONNECTION_LIFETIME
            value: "3600000"
          - name: NEO4J_CONNECTION_TIMEOUT
            value: "30000"
          - name: dbName
            value: "threeedges"
          - name: dbUser
            value: "neo4j"
          - name: dbPass
            valueFrom:
              secretKeyRef:
                key: NEO4J_PASSWORD
                name: prim-configuration-secret
          - name: dbHost
            value: "neo4j+s://db2.3edges.io:7687"
          - name: OIDC_URL
            value: "https://idp.3edges.io/oidc"
          - name: OIDC_CLIENT_ID
            value: "3edgesDataloaderClient"
          - name: OIDC_CLIENT_PWD
            valueFrom:
              secretKeyRef:
                key: CLIENT_PWD_3EDGES
                name: prim-configuration-secret
          - name: CONFIGURATION_URL
            value: "https://3edges.io"
