---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp
  namespace: 3edges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp
  template:
    metadata:
      labels:
        app: idp
        prom: prom-3edges
    spec:
      containers:
        - name: idp
          imagePullPolicy: Always
          image: us-docker.pkg.dev/edges-305901/gcr.io/prim-idp:latest
          env:
            - name: NODE_ENV
              value: "production"
            - name: OIDC_PORT
              value: "3001"
            - name: SERVER_HTTP_CORS_ORIGIN
              value: "*"
            - name: SERVER_HTTP_STRICT_TRANSPORT_SECURITY
              value: "15552000"
            - name: SERVER_HTTP_X_FRAME_OPTIONS
              value: "sameorigin"
            - name: PRIM_ADMIN_EMAIL
              value: "3admin@3edges.io"
            - name: CHECK_VERIFIED
              value: "true"
            - name: NAMING_PROPERTY
              value: "email"
            - name: SUBJECT_TYPE
              value: "NiamUser"
            - name: username
              value: null
            - name: AUTHN_QUERY
              value: "MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = $username) OPTIONAL MATCH (user)-[rel: NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }"
            - name: AUTHN_QUERY_VERIFIED
              value: "MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = $username AND user.isVerified = true) OPTIONAL MATCH (user)-[rel: NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }"
            - name: SOCIAL_URL
              value: "https://social.3edges.io"
            - name: CLAIMS_ARRAY
              value: _id,address,company,country,createDateTime,email,ip,isVerified,mobilePhone,name,roles,subtype,subscriptionLevel
            - name: OIDC_ACCESS_TOKEN_EXPIRE
              value: "24"
            - name: CONTENT_SECURITY_POLICY
              value: "default-src 'self' https://3edges.io https://3edges.io/graphql https://idp.3edges.io http://idp.3edges.io https://3edges.com
                https://ui.qa.3edges.io  https://ui.qa.3edges.io/graphql https://idp.qa.3edges.io http://idp.qa.3edges.io https://accounts.google.com https://www.google.com https://accounts.google.com/gsi/;
                frame-src 'self' https://www.google.com https://accounts.google.com/gsi/;
                base-uri 'self';
                block-all-mixed-content;
                font-src 'self' https: data:;
                frame-ancestors 'self';
                img-src 'self' data:;
                object-src 'none';
                connect-src 'self' https://accounts.google.com/gsi/;
                script-src 'self' https://www.google.com https://accounts.google.com/gsi/client 'unsafe-inline';
                script-src-elem 'self' https://accounts.google.com https://accounts.google.com/gsi/client 'unsafe-inline';
                script-src-attr 'none';
                style-src 'self' https://accounts.google.com/gsi/style https: 'unsafe-inline';"
            - name: ALLOW_HTTP_REDIRECTS
              value: "true"
            - name: PRIM_UI_URL
              value: "https://3edges.io"
            - name: OIDC_AUTHORIZE_ENDPOINT
              value: "/authorize"
            - name: OIDC_TOKEN_ENDPOINT
              value: "/token"
            - name: OIDC_TOKEN_INTROSPECTION_ENDPOINT
              value: "/token/introspection"
            - name: OIDC_ME_ENDPOINT
              value: "/me"
            - name: PROM_METRICS_PREFIX
              value: "ui_idp_"
            - name: PROM_ENABLE_DEFAULT_METRICS
              value: "false"
            - name: IS_IDP_PROXY
              value: "false"
            - name: CLIENT_SECRET_ENC_KEY
              valueFrom:
                secretKeyRef:
                  key: ENC_KEY
                  name: prim-idp-secret
            - name: OIDC_REGISTRATION_URI
              value: "/reg"
            - name: NiamSvcAcc_Client_id
              value: "NiamSvcAcctClient"
            - name: NiamSvcAcc_Client_secret
              valueFrom:
                secretKeyRef:
                  key: NiamSvcAcctClient_secret
                  name: prim-idp-secret
            - name: NiamSvcAcc_username
              value: "NiamSvcAcct"
            - name: NiamSvcAcc_pwd
              valueFrom:
                secretKeyRef:
                  key: NiamSvcAcct_secret
                  name: prim-idp-secret
            - name: OIDC_URL
              value: "https://idp.3edges.io/oidc"
            - name: DB_TYPE
              value: "neo4j"
            - name: DB_VERSION
              value: "v4"
            - name: DB_HOST
              value: "neo4j+s://db2.3edges.io:7687"
            - name: DB_NAME
              value: "threeedges"
            - name: DB_USER
              value: "neo4j"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEO4J_PASSWORD
                  name: prim-idp-secret
            - name: ACCESS_TOKEN_TYPE
              value: "opaque"
            - name: CONSENT_PAGE
              value: "false"
            - name: OIDC_URL_3EDGES
              value: "https://idp.3edges.io/oidc"
            - name: CLIENT_ID_3EDGES
              value: "3edgesConfigClient"
            - name: CLIENT_PWD_3EDGES
              valueFrom:
                secretKeyRef:
                  key: CLIENT_PWD_3EDGES
                  name: prim-configuration-secret
            - name: COOKIE_NNCE
              value: "nnce"
            - name: COOKIE_PRIMSCOOKIE
              value: "primscookie"
            - name: COOKIE_NID
              value: "_nid"
            - name: COOKIE_PKEY
              value: "pkey"
            - name: COOKIE_PROXY_NAMING
              value: null
            - name: API_NAME
              value: null
            - name: SOCIAL_GOOGLE_CLIENT_ID
              value: "911543339197-u736geahkepncd33u75f8kqqm4hk0250.apps.googleusercontent.com"
            - name: SOCIAL_GOOGLE_OIDC_URL
              value: "https://accounts.google.com"
            - name: SOCIAL_GOOGLE_JWKS_URI
              value: "https://www.googleapis.com/oauth2/v3/certs"
            - name: PRIM_UI_CLIENT_ID
              value: "3edgesUIClient"
            - name: PRIM_UI_CLIENT_PWD
              valueFrom:
                secretKeyRef:
                  key: REACT_APP_OIDC_CLIENT_PWD
                  name: prim-ui-secret
            - name: OIDC_REFRESH_TOKEN_EXPIRE
              value: "24"
            - name: CONFIG_URL
              value: "https://3edges.io/graphql"
            - name: INTERNAL_SECRET
              value: "x-secret"
            - name: DB_RECORDS_BATCH_SIZE
              value: "100"
            - name: REDIS_HOST
              value: "redis-headless"
            - name: REDIS_PORT
              value: "6379"
