---
services:
  prim-dataproxy:
    image: babsy/3edges:dataproxy
    container_name: prim-dataproxy
    build:
      context: ..
    ports:
      - "4044:4044"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./etc/config:/src/etc/config
  prim-configuration:
    image: babsy/3edges:configuration
    container_name: prim-configuration
    build:
      context: ..
    ports:
      - "4005:4005"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./etc/config:/src/etc/config
      - ./etc/log:/src/etc/log/
  prim-idp:
    image: babsy/3edges:idp
    container_name: prim-idp
    build:
      context: ..
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - OIDC_PORT=3001
      - AUTHN_QUERY_VERIFIED=MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = '3admin@3edges.io' AND user.isVerified = true) OPTIONAL MATCH (user)-[rel:NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }
      - AUTHN_QUERY=MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = $username) OPTIONAL MATCH (user)-[rel:NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }
      - IS_IDP_PROXY=false
    volumes:
      - ./etc/config:/src/etc/config
  prim-proxy-idp:
    image: babsy/3edges:proxy-idp
    container_name: prim-idp-proxy
    build:
      context: ..
    ports:
      - "3007:3007"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - OIDC_PORT=3007
      - AUTHN_QUERY=MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = $username) OPTIONAL MATCH (user)-[rel:NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }
      - AUTHN_QUERY_VERIFIED=MATCH (user:$SUBJECT_TYPE) WHERE (user.$NAMING_PROPERTY = $username AND user.isVerified = true) OPTIONAL MATCH (user)-[rel:NIAM_BELONGS_TO | NIAM_ADMINISTERS]->(tenant:NiamTenant) WITH COLLECT(DISTINCT CASE WHEN user.email = '$PRIM_ADMIN_EMAIL' THEN 'Roles.SuperAdmin' WHEN type(rel) = 'NIAM_ADMINISTERS' THEN 'Roles.Admin' WHEN type(rel) = 'NIAM_BELONGS_TO' THEN 'Roles.User' END) as roles, user, '$SUBJECT_TYPE' as subtype RETURN user{ .*, roles, subtype }
      - IS_IDP_PROXY="true"
    volumes:
      - ./etc/config:/src/etc/config
  prim-cluster:
    image: babsy/3edges:cluster
    container_name: prim-cluster
    build:
      context: ..
    ports:
      - "3333:3333"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  prim-authorization:
    image: babsy/3edges:authorization
    container_name: prim-authorization
    build:
      context: ..
    ports:
      - "5055:5055"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./etc/config:/src/etc/config
  prim-client-ui:
    image: babsy/3edges:ui
    container_name: prim-client-ui
    build:
      context: ..
    ports:
      - "3045:3045"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  prim-dataloader:
    image: babsy/3edges:dataloader
    container_name: prim-dataloader
    build:
      context: ..
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  prim-dataloader-ui:
    image: babsy/3edges:dataloader-ui
    container_name: prim-dataloader-ui
    build:
      context: ..
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  prim-ui:
    image: babsy/3edges:ui
    container_name: prim-ui
    build:
      context: ..
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development